### ISSUE TITLE
Always redirects to sandbox.

### ISSUE THREAD

**Issue by mforcer** [ishannz/laravel-evernote-cloud#4]
The app always redirects to sandbox.evernote.com regardless of what is set in .env

EVERNOTE_SANDBOX=false

still goes to sandbox.

Regards

**Comment by mforcer** [comment]
If you're like me and don't properly read API notes, here is some info: All API requests a forwarded to Evernote's sandbox, you need to 'apply' for production API.

**Comment by patelmm** [comment]
I have same issue, already activated production key and i got email form evernote. Still getting issue and not able to redirect to evernote site, it's showing empty page.

**Comment by ishannz** [comment]
@patelmm, which Laravel version are you using?

**Comment by patelmm** [comment]
Laravel 8
